name: update_workshop_develop

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  linter:
    uses: CapsAdmin/pac3/.github/workflows/lua_linter.yaml@develop

  update-workshop-develop:
      if: github.repository == 'CapsAdmin/pac3'
      needs: linter
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Publish to Steam Workshop
          uses: vurv78/gmod-upload@v0.1.3
          env:
            STEAM_USERNAME: ${{ secrets.STEAM_NAME }}
            STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
          with:
            id: '3038093543'
            changelog: ${{ github.event.head_commit.message }}
            config: "addon_develop.json"